package nihongo

import "regexp"

var neologdnRule = [...]replacer{
	// replace Zenkaku Alphabet and numbers
	&rep{"０", "0"},
	&rep{"１", "1"},
	&rep{"２", "2"},
	&rep{"３", "3"},
	&rep{"４", "4"},
	&rep{"５", "5"},
	&rep{"６", "6"},
	&rep{"７", "7"},
	&rep{"８", "8"},
	&rep{"９", "9"},
	&rep{"ａ", "a"},
	&rep{"ｂ", "b"},
	&rep{"ｃ", "c"},
	&rep{"ｄ", "d"},
	&rep{"ｅ", "e"},
	&rep{"ｆ", "f"},
	&rep{"ｇ", "g"},
	&rep{"ｈ", "h"},
	&rep{"ｉ", "i"},
	&rep{"ｊ", "j"},
	&rep{"ｋ", "k"},
	&rep{"ｌ", "l"},
	&rep{"ｍ", "m"},
	&rep{"ｎ", "n"},
	&rep{"ｏ", "o"},
	&rep{"ｐ", "p"},
	&rep{"ｑ", "q"},
	&rep{"ｒ", "r"},
	&rep{"ｓ", "s"},
	&rep{"ｔ", "t"},
	&rep{"ｕ", "u"},
	&rep{"ｖ", "v"},
	&rep{"ｗ", "w"},
	&rep{"ｘ", "x"},
	&rep{"ｙ", "y"},
	&rep{"ｚ", "z"},
	&rep{"Ａ", "A"},
	&rep{"Ｂ", "B"},
	&rep{"Ｃ", "C"},
	&rep{"Ｄ", "D"},
	&rep{"Ｅ", "E"},
	&rep{"Ｆ", "F"},
	&rep{"Ｇ", "G"},
	&rep{"Ｈ", "H"},
	&rep{"Ｉ", "I"},
	&rep{"Ｊ", "J"},
	&rep{"Ｋ", "K"},
	&rep{"Ｌ", "L"},
	&rep{"Ｍ", "M"},
	&rep{"Ｎ", "N"},
	&rep{"Ｏ", "O"},
	&rep{"Ｐ", "P"},
	&rep{"Ｑ", "Q"},
	&rep{"Ｒ", "R"},
	&rep{"Ｓ", "S"},
	&rep{"Ｔ", "T"},
	&rep{"Ｕ", "U"},
	&rep{"Ｖ", "V"},
	&rep{"Ｗ", "W"},
	&rep{"Ｘ", "X"},
	&rep{"Ｙ", "Y"},
	&rep{"Ｚ", "Z"},

	// replace Zenkaku Katakana
	&rep{"ｶﾞ", "ガ"},
	&rep{"ｷﾞ", "ギ"},
	&rep{"ｸﾞ", "グ"},
	&rep{"ｹﾞ", "ゲ"},
	&rep{"ｺﾞ", "ゴ"},
	&rep{"ｻﾞ", "ザ"},
	&rep{"ｼﾞ", "ジ"},
	&rep{"ｽﾞ", "ズ"},
	&rep{"ｾﾞ", "ゼ"},
	&rep{"ｿﾞ", "ゾ"},
	&rep{"ﾀﾞ", "ダ"},
	&rep{"ﾁﾞ", "ヂ"},
	&rep{"ﾂﾞ", "ヅ"},
	&rep{"ﾃﾞ", "デ"},
	&rep{"ﾄﾞ", "ド"},
	&rep{"ﾊﾞ", "バ"},
	&rep{"ﾋﾞ", "ビ"},
	&rep{"ﾌﾞ", "ブ"},
	&rep{"ﾍﾞ", "ベ"},
	&rep{"ﾎﾞ", "ボ"},
	&rep{"ﾊﾟ", "パ"},
	&rep{"ﾋﾟ", "ピ"},
	&rep{"ﾌﾟ", "プ"},
	&rep{"ﾍﾟ", "ペ"},
	&rep{"ﾎﾟ", "ポ"},

	&rep{"ｱ", "ア"},
	&rep{"ｲ", "イ"},
	&rep{"ｳ", "ウ"},
	&rep{"ｴ", "エ"},
	&rep{"ｵ", "オ"},
	&rep{"ｶ", "カ"},
	&rep{"ｷ", "キ"},
	&rep{"ｸ", "ク"},
	&rep{"ｹ", "ケ"},
	&rep{"ｺ", "コ"},
	&rep{"ｻ", "サ"},
	&rep{"ｼ", "シ"},
	&rep{"ｽ", "ス"},
	&rep{"ｾ", "セ"},
	&rep{"ｿ", "ソ"},
	&rep{"ﾀ", "タ"},
	&rep{"ﾁ", "チ"},
	&rep{"ﾂ", "ツ"},
	&rep{"ﾃ", "テ"},
	&rep{"ﾄ", "ト"},
	&rep{"ﾅ", "ナ"},
	&rep{"ﾆ", "ニ"},
	&rep{"ﾇ", "ヌ"},
	&rep{"ﾈ", "ネ"},
	&rep{"ﾉ", "ノ"},
	&rep{"ﾊ", "ハ"},
	&rep{"ﾋ", "ヒ"},
	&rep{"ﾌ", "フ"},
	&rep{"ﾍ", "ヘ"},
	&rep{"ﾎ", "ホ"},
	&rep{"ﾏ", "マ"},
	&rep{"ﾐ", "ミ"},
	&rep{"ﾑ", "ム"},
	&rep{"ﾒ", "メ"},
	&rep{"ﾓ", "モ"},
	&rep{"ﾔ", "ヤ"},
	&rep{"ﾕ", "ユ"},
	&rep{"ﾖ", "ヨ"},
	&rep{"ﾗ", "ラ"},
	&rep{"ﾘ", "リ"},
	&rep{"ﾙ", "ル"},
	&rep{"ﾚ", "レ"},
	&rep{"ﾛ", "ロ"},
	&rep{"ﾜ", "ワ"},
	&rep{"ｦ", "ヲ"},
	&rep{"ﾝ", "ン"},
	&rep{"ｧ", "ァ"},
	&rep{"ｨ", "ィ"},
	&rep{"ｩ", "ゥ"},
	&rep{"ｪ", "ェ"},
	&rep{"ｫ", "ォ"},
	&rep{"ｯ", "ッ"},
	&rep{"ｬ", "ャ"},
	&rep{"ｭ", "ュ"},
	&rep{"ｮ", "ョ"},

	// replace characters which like Hyphen or Minus sign
	&rep{"\u02D7", "-"},
	&rep{"\u058A", "-"},
	&rep{"\u2010", "-"},
	&rep{"\u2011", "-"},
	&rep{"\u2012", "-"},
	&rep{"\u2013", "-"},
	&rep{"\u2043", "-"},
	&rep{"\u207B", "-"},
	&rep{"\u208B", "-"},
	&rep{"\u2212", "-"},

	// replace characters that like Japanese Prolonged Sound Mark "ー"
	&rep{"\u2014", "ー"},
	&rep{"\u2015", "ー"},
	&rep{"\u2500", "ー"},
	&rep{"\u2501", "ー"},
	&rep{"\uFE63", "ー"},
	&rep{"\uFF70", "ー"},

	// replace characters that like two or more occurrences of Japanese Prolonged Sound Mark "ー"
	&regRep{regexp.MustCompile(`ー+`), "ー"},

	// delete characters that like tilde
	&rep{"~", ""},
	&rep{"∼", ""},
	&rep{"∾", ""},
	&rep{"〰", ""},
	&rep{"～", ""},

	// replace Zenkaku Symbols below to Hankaku
	// ！”＃＄％＆’（）＊＋，−．／：；＜＞？＠［￥］＾＿｀｛｜｝
	&rep{"！", "!"},
	&rep{"”", "\""},
	&rep{"＃", "#"},
	&rep{"＄", "$"},
	&rep{"％", "%"},
	&rep{"＆", "&"},
	&rep{"’", "'"},
	&rep{"（", "("},
	&rep{"）", ")"},
	&rep{"＊", "*"},
	&rep{"＋", "+"},
	&rep{"，", ","},
	&rep{"－", "-"},
	&rep{"．", "."},
	&rep{"／", "/"},
	&rep{"：", ":"},
	&rep{"；", ";"},
	&rep{"＜", "<"},
	&rep{"＞", ">"},
	&rep{"？", "?"},
	&rep{"＠", "@"},
	&rep{"［", "["},
	&rep{"￥", "¥"},
	&rep{"］", "]"},
	&rep{"＾", "^"},
	&rep{"＿", "_"},
	&rep{"｀", "`"},
	&rep{"｛", "{"},
	&rep{"｜", "|"},
	&rep{"｝", "}"},

	// replace Hankaku Symbols below to Zenkaku
	// ｡､･=｢｣
	&rep{"｡", "。"},
	&rep{"､", "、"},
	&rep{"･", "・"},
	&rep{"゛", "ﾞ"},
	&rep{"゜", "ﾟ"},
	&rep{"｢", "「"},
	&rep{"｣", "」"},
	&rep{"=", "＝"},

	// replace Zenkaku Space (　) to Hankaku Space ( )
	&rep{"　", " "},

	// replace characters that like two or more occurrences of Hankaku Space
	&regRep{regexp.MustCompile(` +`), " "},

	// Delete heading Hankaku Space and tailing Hankaku Space
	&regRep{regexp.MustCompile(`^ `), ""},
	&regRep{regexp.MustCompile(` $`), ""},

	// Delete Hankaku Space among Hiragana, Katakana, and Kanji
	&regRep{regexp.MustCompile(`([^a-zA-Z0-9]) ([^a-zA-Z0-9])`), "$1$2"},
	&regRep{regexp.MustCompile(`([^a-zA-Z0-9]) ([^a-zA-Z0-9])`), "$1$2"},

	// Delete Hankaku Space between Hiragana, Katakana, and Kanji, and Alphabet
	&regRep{regexp.MustCompile(`([^a-zA-Z0-9]) ([a-zA-Z0-9])`), "$1$2"},
	&regRep{regexp.MustCompile(`([a-zA-Z0-9]) ([^a-zA-Z0-9])`), "$1$2"},
}

func WithNeologdn(s string) (string, error) {
	for i := range neologdnRule {
		s = neologdnRule[i].Replace(s)
	}
	return s, nil
}
